### ISSUE TITLE
Missing data files?

### ISSUE THREAD

**Issue by xrotwang** [stedt-project/sss#1]
Are the actual data files supposed to be available here: https://github.com/stedt-project/sss/tree/master/archiving/dump ?

**Comment by jblowe** [comment]
No, the only thing that is here in this repo is code!

The directory you cite is part of the code that creates the data archive.

If you are interested in getting the data (available in beta version at the moment), please email "stedt@berkeley.edu", or email me directly ("jblowe@berkeley.edu")
